### ISSUE TITLE
In-Memory Databases are not really pooled/shared

### ISSUE THREAD

**Issue by Progdrasil** [ivanceras/r2d2-sqlite#39] opened 2020-11-07 23:47 UTC
It seems the issue #1 has come back. 

Everything works great when using a file, but when comes time for testing, i'm using an in-memory database. However it seems to not be connected in any way.

I seems that this issue has been brought back since f0a7bdd.

Here's a sample code which reproduces the issue, taken directly from the library level example, just switched out the `file` to `memory`

```rust
#[test]
    fn test_connection_pool() -> anyhow::Result<()> {
        let manager = SqliteConnectionManager::memory();
        let pool = r2d2::Pool::new(manager).unwrap();

        pool.get()?.execute(
            "CREATE TABLE IF NOT EXISTS foo (bar INTEGER)",
            rusqlite::params![],
        )?;

        // Pool default size is 10
        (0..10)
            .map(|i| {
                let pool = pool.clone();
                std::thread::spawn(move || {
                    let conn = pool.get().unwrap();
                    conn.execute("INSERT INTO foo (bar) VALUES (?)", rusqlite::params![i])
                        .unwrap();
                })
            })
            // Fire off the threads
            .collect::<Vec<_>>()
            .into_iter()
            .map(std::thread::JoinHandle::join)
            .collect::<Result<(), _>>()
            .unwrap();

        Ok(())
    }
```
This example gives the following output

```rust
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some("no such table: foo"))', src/mod.rs:142:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test tests::test_connection_pool ... FAILED
```

However, using the suggestion from [Gwenn's comment](https://github.com/ivanceras/r2d2-sqlite/issues/1#issuecomment-153597060) works.

```rust
use rusqlite::OpenFlags as of;
let manager = SqliteConnectionManager::file("file:dummy.db?mode=memory&cache=shared")
             .with_flags(of::SQLITE_OPEN_URI | of::SQLITE_OPEN_CREATE | of::SQLITE_OPEN_READ_WRITE);
```

While this works, it feels kind of ~~hacky~~ unergonomic , would there be a way to make the `memory` function behave in a similar fashion?

**Comment by infogulch** [comment] 2020-11-08 21:38
The SQLite documentation on [In-Memory Databases](https://www.sqlite.org/inmemorydb.html) might be of interest:

> instead of passing the name of a real disk file into one of the [connection initialization] functions, pass in the string ":memory:". ... When this is done, no disk file is opened. Instead, a new database is created purely in memory. The database ceases to exist as soon as the database connection is closed.
> 
> Every :memory: database is distinct from every other. So, opening two database connections each with the filename ":memory:" will create two independent in-memory databases.

Since each `:memory:` connection is a separate database, this makes `:memory:` unsuitable for `SqliteConnectionManager` (imho) since the manager presumably manages connections to a shared data store (as evidenced by the example that you would like to get working).

---

The section [In-memory Databases And Shared Cache](https://www.sqlite.org/inmemorydb.html#sharedmemdb) suggests other potential options:

1. `file::memory:?cache=shared` with URI flag would make a process-level "singleton" database.  [1] I think this would be better than the current behavior for `memory()` (which is kinda broken), but it invites the opportunity for two separate components of a program to clash when they *don't* expect to get the same db.  (This [StackOverflow answer](https://stackoverflow.com/a/15720872) suggests this method.)

1. `file:memdb1?mode=memory&cache=shared`, what do you know this is what Gwenn's comment uses.  Note that the `memdb1` part is basically a key and (I think) doesn't represent a real file.  Given that this is explicitly supported and suggested by SQLite itself I don't think it's fair to call it "hacky", though I would sympathize with an argument that it could be more ergonomic to use.

    > If two or more distinct but shareable in-memory databases are needed in a single process, then the mode=memory query parameter can be used with a URI filename to create a named in-memory database...
    > When an in-memory database is named in this way, it will only share its cache with another connection that uses exactly the same name. 

From an API behavior/correctness perspective, I would greatly prefer moving towards option 2 and changing the signature of `SqliteConnectionManager::memory()` to take a parameter that is used to fill in the key portion of the URI, and otherwise just reproduce Gwenn's suggestion.  This would enable users of the library to avoid accidental clashes by naming the connection something unique to their program (or even make it configurable), and still remain pretty ergonomic.

---

**However**, even if you do all that you still have another issue:

> The database is automatically deleted and memory is reclaimed when the last connection to the database closes.

I don't know how you could get around this other than taking out a connection after the manager initializes and just "leaking" it until the program exits, because otherwise every time the manager decides to drop the last connection all the data will be lost.

**Comment by Progdrasil** [comment] 2020-11-12 16:29
Thanks @infogulch for that very detailed and enlightening response! Sorry for the term "hacky" perhaps not the right term, i'll fix that.

I do agree that adding a method for a shared in-memory database would make this much more ergonomic.

I'm not very familiar with r2d2's internals yet, so take this next suggestion/question with a grain of salt. Since the database is dropped once the last reference to that key is closed. Would it be possible to put an infinite (or close enough to it) timeout on the pool connections? Therefor forcing the pool to always keep at least one connection open for the lifetime of the program. Although I'm guessing this introduces a bunch of other behavioral issues.

**Comment by infogulch** [comment] 2020-11-12 22:17
I'm glad you found it helpful!  No worries about terminology, I just didn't want you to inadvertently pass up a good option just because its got a bit of dirt on its face; that just means we have to polish it! 😸

Yeah, a pool timeout configuration may make this feasible, I hadn't considered that.  I'm unfamiliar with exactly how the pool retains & releases connections, so we may want investigate this option further in the context of r2d2.

**Comment by ongardie** [comment] 2021-02-09 00:00
I, too, ran into this problem and only found this report hours later. I tried `file:dummy.db?mode=memory&cache=shared` with some limited success, but I found that the shared cache makes SQLite behave differently (worse) with respect to table-level locking. Even though I was using WAL mode, writes would cause concurrent readers to return an SQLITE_LOCKED error. See https://sqlite.org/sharedcache.html for more info.

I don't see a general-purpose way to implement `SqliteConnectionManager::memory()` without such surprises. I concluded that the best thing for my purpose was to create a normal database on disk in a temporary directory, then just delete its files later.

**Comment by OJFord** [comment] 2021-02-24 21:19
Even with the other issues, I think the result of:
```rust
let mgr = r2d2_sqlite::SqliteConnectionManager::memory();
let pool = r2d2::Pool::new(mgr)?;
```

should be one of the (under the hood) `file:` options presented above, as it is it just doesn't work, and is very confusing.

I thought I was missing something like implicit transactions and not doing what I needed to to commit - the only way it worked was when I dropped the previous connection before `get`ting and using another, so I thought it was commiting/flushing/syncing on connection close, which I can't call manually when acquired from the pool.

But of course it wasn't that, reading this I now realise it's because the 'next' connection is really picking up the same one from the pool, and hence the same `:memory:` database.

I assume `memory()` has to be implemented (or not? could it just be `unimplemented!()`?) for r2d2, but as it is it might as well not be, I really think _anything_ would be better than this sort of confusing pretends-to-work-depending-how-you-use-it situation.

No disrespect to the work that's gone in to this library at all of course, and I fully understand there's not a trivial clearly-correct solution; I just think the present implementation is worse (because it's not what anyone expects, except by chance) than not having one at all.

Glad to find this issue though, was tearing my hair out! 😄

**Comment by xmo-odoo** [comment] 2022-02-17 14:27
> From an API behavior/correctness perspective, I would greatly prefer moving towards option 2 and changing the signature of `SqliteConnectionManager::memory()` to take a parameter that is used to fill in the key portion of the URI, and otherwise just reproduce Gwenn's suggestion. This would enable users of the library to avoid accidental clashes by encouraging them to name the connection something unique to their program (or even make it configurable), and still remain pretty ergonomic.

Why not just create synthetic names internally (e.g. using an `AtomicUsize`?) The key doesn't really seem relevant to the average user of the library.

> > The database is automatically deleted and memory is reclaimed when the last connection to the database closes.
> 
> I don't know how you could get around this other than taking out a connection after the pool initializes and just "leaking" it until the program exits (or when pool is dropped or something), because otherwise every time the pool decides to drop the last connection all the data will be lost. (Now _that's_ what I would call "hacky")

But wouldn't things work fine if `memory` simply rejected a `min_idle` of `Some(0)`, or replaced that by `Some(1)`? Or will the connection pool still delete connections even if it has no more than `min_idle`?

**Closed** 2023-05-15 05:42 UTC
